package com.ilaotan.application.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return get("id");
    }

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.String getMenuName() {
        return get("menu_name");
    }

    public void setMenuName(java.lang.String menuName) {
        set("menu_name", menuName);
    }

    public java.lang.String getMenuUrl() {
        return get("menu_url");
    }

    public void setMenuUrl(java.lang.String menuUrl) {
        set("menu_url", menuUrl);
    }

    public java.lang.String getMenuSn() {
        return get("menu_sn");
    }

    public void setMenuSn(java.lang.String menuSn) {
        set("menu_sn", menuSn);
    }

    public java.lang.String getMenuType() {
        return get("menu_type");
    }

    public void setMenuType(java.lang.String menuType) {
        set("menu_type", menuType);
    }

    public java.lang.Integer getMenuParentId() {
        return get("menu_parent_id");
    }

    public void setMenuParentId(java.lang.Integer menuParentId) {
        set("menu_parent_id", menuParentId);
    }

    public java.lang.String getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.lang.String createTime) {
        set("create_time", createTime);
    }

    public java.lang.String getCreater() {
        return get("creater");
    }

    public void setCreater(java.lang.String creater) {
        set("creater", creater);
    }

}
