package com.jfinalD.application.system.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends Model<M> implements IBean {

    public java.lang.Long getId() {
        return get("id");
    }

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getRoleId() {
        return get("role_id");
    }

    public void setRoleId(java.lang.Long roleId) {
        set("role_id", roleId);
    }

    public java.lang.Long getPermissionId() {
        return get("permission_id");
    }

    public void setPermissionId(java.lang.Long permissionId) {
        set("permission_id", permissionId);
    }

}
