package com.jfinalD.application.system.model;

import com.jfinalD.application.system.model.base.BaseRole;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();

	public List<String> findRoleByUserId(Long id){
		List<Role> roleList = super.find("select r.name from system_user_role ur INNER JOIN system_role r on ur.role_id = r.id where ur.user_id=?",id);
		List<String> list = new ArrayList<String>();
		for(Role role : roleList){
			list.add(role.getStr("name"));
		}
		return list;
	}
}
