package com.jfinalD.application.system.model;

import com.jfinalD.application.system.model.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
    public static final UserRole dao = new UserRole().dao();
}
