package com.jfinalD.application.system.model;

import com.jfinal.plugin.activerecord.Page;
import com.jfinalD.application.system.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	public User findByUsername(String username){
		return super.findFirst("select u.id,r.id as roleId,username,password,salt,is_locked,r.description,r.name as rolename from system_user u " +
				"INNER JOIN system_user_role ur on u.id = ur.user_id " +
				"INNER JOIN system_role r on ur.role_id = r.id " +
				"where username=? and is_locked=0",username);
	}

	public User findByUserId(long id){
		return super.findFirst(
				"select u.id,r.id as roleId,username,password,salt,is_locked,r.description,r.name as rolename from system_user u " +
				"INNER JOIN system_user_role ur on u.id = ur.user_id " +
				"INNER JOIN system_role r on ur.role_id = r.id " +
				"where u.id=?",id);
		//return super.findFirst("select u.id,u.username,u.password,u.salt,u.is_locked from system_user u where u.id=?",id);
	}

	public Page<User> paginate(int pageNo,int pageSize){

		return User.dao.paginate(pageNo, pageSize, "select u.username,u.is_locked,u.id,r.name,r.description ", "from system_user u "+
				"LEFT JOIN system_user_role ur on ur.user_id = u.id "+
				"LEFT JOIN system_role r on r.id = ur.role_id ");
	}

}
