package com.ilaotan.application.system.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

    public static void mapping(ActiveRecordPlugin arp) {
        arp.addMapping("sec_permission", "id", Permission.class);
        arp.addMapping("sec_role", "id", Role.class);
        arp.addMapping("sec_role_permission", "id", RolePermission.class);
        arp.addMapping("sec_user", "id", User.class);
        arp.addMapping("sec_user_info", "id", UserInfo.class);
        arp.addMapping("sec_user_role", "id", UserRole.class);
    }
}

