package com.ilaotan.application.system.model;

import com.ilaotan.application.system.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
    public static final RolePermission dao = new RolePermission().dao();
}
