package com.ilaotan.application.system.model;

import com.ilaotan.application.system.model.base.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
    public static final UserInfo dao = new UserInfo().dao();
}
